name: Dependency Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Job 1
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run Job 2
        run: echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Run Job 3
        run: echo "This is Job 3"